# Generated by Django 3.2.17 on 2023-03-14 10:28

from django.db import migrations
from django.db import models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Сообщение для нас',
                        verbose_name='сообщение для нас',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'status',
                    models.TextField(
                        choices=[
                            ('получено', 'получено'),
                            ('в обработке', 'в обработке'),
                            ('ответ дан', 'ответ дан'),
                        ],
                        default='получено',
                        verbose_name='статус',
                    ),
                ),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackDataUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        help_text='Необходимо ввести корректную почту',
                        max_length=254,
                        verbose_name='почта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'данные пользователя',
                'verbose_name_plural': 'данные пользователя',
                'default_related_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'files',
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to=feedback.models.FeedbackFiles.saving_path,
                        verbose_name='файлы',
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        default=None,
                        help_text='прикрепите файлы',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='feedback.feedback',
                        verbose_name='файлы',
                    ),
                ),
            ],
            options={
                'verbose_name': 'файлы фидбека',
                'verbose_name_plural': 'файлы фидбека',
                'default_related_name': 'files',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='data_user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='feedback.feedbackdatauser',
                verbose_name='данные пользователя',
            ),
        ),
    ]
