# Generated by Django 3.2.17 on 2023-03-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(
                help_text='Необходимо ввести корректную почту',
                max_length=254,
                verbose_name='Почта',
            ),
        ),
    ]
