# Generated by Django 3.2.17 on 2023-03-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdatauser',
            name='email',
            field=models.EmailField(
                help_text='необходимо ввести корректную почту',
                max_length=254,
                verbose_name='почта',
            ),
        ),
    ]
