# Generated by Django 3.2.17 on 2023-03-29 15:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0005_auto_20230317_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Date of creation',
                verbose_name='date of creation',
            ),
        ),
    ]
