# Generated by Django 3.2.17 on 2023-03-19 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'birthday',
                    models.DateField(
                        blank=True,
                        help_text='Enter date of birth',
                        null=True,
                        verbose_name='birthday',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        help_text='Enter profile picture',
                        null=True,
                        upload_to='',
                        verbose_name='profile picture',
                    ),
                ),
                (
                    'coffee_count',
                    models.BigIntegerField(
                        default=0,
                        help_text='Number of user requests for coffee',
                        verbose_name='coffee count',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'additional field',
                'verbose_name_plural': 'additional fields',
                'default_related_name': 'profile',
            },
        ),
    ]
