# Generated by Django 3.2.17 on 2023-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Enter profile picture',
                null=True,
                upload_to='uploads/user_image/',
                verbose_name='profile picture',
            ),
        ),
    ]
