# Generated by Django 3.2.17 on 2023-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230323_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_blocking_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Account lockout date', null=True, verbose_name='account blocking date'),
        ),
    ]
