# Generated by Django 3.2.17 on 2023-03-28 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0018_alter_item_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={
                'default_related_name': 'ratings',
                'verbose_name': 'rating',
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.AlterField(
            model_name='grade',
            name='item',
            field=models.ForeignKey(
                help_text='Product that has been rated',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ratings',
                to='catalog.item',
                verbose_name='item',
            ),
        ),
        migrations.AlterField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(
                help_text='The user who left the rating',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ratings',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
