# Generated by Django 3.2.17 on 2023-03-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0018_alter_item_text'),
        ('rating', '0002_auto_20230328_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='item',
            field=models.ForeignKey(
                help_text='Product that has been rated',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='grades',
                to='catalog.item',
                verbose_name='item',
            ),
        ),
    ]
