# Generated by Django 3.2.17 on 2023-03-29 15:31

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_auto_20230329_1831"),
        ("rating", "0003_alter_grade_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date of creation",
                verbose_name="date of creation",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="item",
            field=models.ForeignKey(
                help_text="Product that has been rated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="catalog.item",
                verbose_name="item",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("item", "user"), name="unique_rating"
            ),
        ),
    ]
