# Generated by Django 3.2.17 on 2025-05-22 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0005_alter_grade_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date of creation",
                verbose_name="date of creation",
            ),
        ),
    ]
