# Generated by Django 3.2.17 on 2023-02-20 18:42

import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_auto_20230219_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={
                'default_related_name': 'items',
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тэг', 'verbose_name_plural': 'тэги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Максимум 200 символов. Можно использовать только буквы цифры и знаки подчеркивания и тире.',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Максимум 200 символов. Можно использовать только буквы цифры и знаки подчеркивания и тире.',
                max_length=200,
                unique=True,
                verbose_name='символьный код',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name='вес'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='У предмета должна быть категория.',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='items',
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Максимум 200 символов. Можно использовать только буквы цифры и знаки подчеркивания и тире.',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                help_text='У предмета должн быть хотя бы 1 тэг.',
                related_name='items',
                to='catalog.Tag',
                verbose_name='тэги',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='В тексте должно быть одно из слов: роскошно, превосходно.',
                validators=[catalog.validators.ValidateMustContain],
                verbose_name='описание',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Максимум 200 символов. Можно использовать только буквы цифры и знаки подчеркивания и тире.',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                help_text='Максимум 200 символов. Можно использовать только буквы цифры и знаки подчеркивания и тире.',
                max_length=200,
                unique=True,
                verbose_name='символьный код',
            ),
        ),
    ]
