# Generated by Django 3.2.17 on 2023-02-22 13:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0006_auto_20230222_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(
                help_text='Ключевые слова',
                max_length=150,
                null=True,
                verbose_name='ключевые слова',
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.CharField(
                help_text='Ключевые слова',
                max_length=150,
                null=True,
                verbose_name='ключевые слова',
            ),
        ),
    ]
