# Generated by Django 3.2.17 on 2023-02-22 14:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_auto_20230222_1626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="keywords",
            field=models.CharField(
                editable=False,
                help_text="Ключевые слова",
                max_length=150,
                null=True,
                verbose_name="ключевые слова",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="keywords",
            field=models.CharField(
                editable=False,
                help_text="Ключевые слова",
                max_length=150,
                null=True,
                verbose_name="ключевые слова",
            ),
        ),
    ]
