# Generated by Django 3.2.17 on 2023-02-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0008_auto_20230222_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='keywords',
        ),
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                help_text='Нормализированное имя',
                max_length=150,
                null=True,
                verbose_name='Нормализированное имя',
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                help_text='Нормализированное имя',
                max_length=150,
                null=True,
                verbose_name='Нормализированное имя',
            ),
        ),
    ]
