# Generated by Django 3.2.17 on 2023-02-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0008_auto_20230222_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(
                editable=False,
                help_text='Ключевые слова',
                max_length=150,
                verbose_name='ключевые слова',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='keywords',
            field=models.CharField(
                editable=False,
                help_text='Ключевые слова',
                max_length=150,
                verbose_name='ключевые слова',
            ),
        ),
    ]
