# Generated by Django 3.2.17 on 2023-02-28 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0010_galleryimagesitem_mainimageitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimagesitem',
            options={
                'default_related_name': 'gallery_images',
                'verbose_name': 'изображение',
                'verbose_name_plural': 'галерея изображений',
            },
        ),
    ]
