# Generated by Django 3.2.17 on 2023-03-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0013_auto_20230308_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
