# Generated by Django 3.2.17 on 2023-03-29 15:31

import django.core.validators
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0018_alter_item_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'default_related_name': 'category',
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True, help_text='Published', verbose_name='published'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text='Enter weight please',
                validators=[
                    django.core.validators.MinValueValidator(
                        0, 'Minimum number to enter 0'
                    ),
                    django.core.validators.MaxValueValidator(
                        32767, 'The maximum number to enter is 32767'
                    ),
                ],
                verbose_name='weight',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Date of creation',
                verbose_name='date of creation',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(
                default=False,
                help_text='Show on homepage',
                verbose_name='show on homepage',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True, help_text='Published', verbose_name='published'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                help_text='Update date',
                verbose_name='update date',
            ),
        ),
        migrations.AlterField(
            model_name='mainimageitem',
            name='items',
            field=models.OneToOneField(
                blank=True,
                help_text='Enter main image please',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='main_image',
                to='catalog.item',
                verbose_name='main image',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(
                default=True, help_text='Published', verbose_name='published'
            ),
        ),
    ]
